# Generated by Django 4.1.7 on 2023-04-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, max_length=200, verbose_name='摘要'),
        ),
    ]
